### ISSUE TITLE
hexo-renderer-sass using error

### ISSUE THREAD

**Issue by dokinchan** [zalando-incubator/hexo-theme-doc#101]
https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/sass-styles.html
like the link, I created source/styles/doc.scss in the project root directory
and wrote down only this codes;
 $doc-color-primary: red; // set primary color to "red"
 @import "../node_modules/hexo-theme-doc/_doc.scss"
and it causes the error when I "hexo g"
 it says
"Error: File to import not found or unreadable: ../node_modules/hexo-theme-doc/_doc.scss. 
Parent style sheet: /Users/boyeon/study/blog/dokinchan/source/styles/doc.scss"

What should I do??

## Specifications

  - NodeJS Version: 8.9.4
  - NPM Version: 5.6.0
  - OS: mac
  - Hexo Version: 3.4.4

**Comment by rbarilani** [comment]
Hi @dokinchan, there is a typo in the documentation page 

with:

```sass
@import "../../node_modules/hexo-theme-doc/_doc.scss"
/* NOT: @import "../node_modules/hexo-theme-doc/_doc.scss" */
````
It should work.

**Comment by rbarilani** [comment]
@dokinchan We are having issues with SCSS imports and `npm`. Working on a proper fix.

**Comment by walkccc** [comment]
Hi @rbarilani, after change from `/* NOT: @import "../node_modules/hexo-theme-doc/_doc.scss" */``@import "../../node_modules/hexo-theme-doc/_doc.scss"`

**Comment by walkccc** [comment]
Hi @rbarilani, after changing the file in "/{rootFolder}/source/styles/doc.scss"(This was added manually mentioned by @dokinchan earlier.)

from `/* NOT: @import "../node_modules/hexo-theme-doc/_doc.scss" */` 
to `@import "../../node_modules/hexo-theme-doc/_doc.scss"`

It still not work for me.

The error messages:

> ~/CLRS/source(CLRS-sources*) » hexo s                  jay@Jays-MacBook-Pro
INFO  Start processing
Error: File to import not found or unreadable: ../../../node_modules/dress-code/dist/sass/dress-code.
Parent style sheet: /Users/Jay/CLRS/node_modules/hexo-theme-doc/source/style/_doc/index.scss
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: File to import not found or unreadable: ../../../node_modules/dress-code/dist/sass/dress-code.
Parent style sheet: /Users/Jay/CLRS/node_modules/hexo-theme-doc/source/style/_doc/index.scss
    at Object.module.exports.renderSync (/Users/Jay/CLRS/node_modules/node-sass/lib/index.js:439:16)
    at Hexo.<anonymous> (/Users/Jay/CLRS/node_modules/hexo-renderer-sass/lib/renderer.js:25:23)
    at /Users/Jay/CLRS/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/Users/Jay/CLRS/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Jay/CLRS/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Jay/CLRS/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/Jay/CLRS/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/Jay/CLRS/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/Jay/CLRS/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Jay/CLRS/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

How can I do? Thanks!

# Specifications

- NodeJS Version: 8.9.4
- NPM Version: 5.6.0
- OS: macOS High Sierra version 10.13.3
- Hexo Version: 3.5.0

**Comment by rbarilani** [comment]
@dokinchan @walkccc working on a change that should fix the problem in the next release [here](https://github.com/zalando-incubator/hexo-theme-doc/pull/103). The change when merged will IMHO improve sass mechanism avoiding relative imports and fix the reported problem.

**Comment by rkuzsma** [comment]
I confirmed @rbarilani 's change fixes the issue. To apply his change to your project, run `npm i hexo-theme-doc@1.0.0-rc --save`
