### ISSUE TITLE
`Maximum call stack size exceeded` when swagger.yaml spec contains circular $ref

### ISSUE THREAD

**Issue by ouadi** [zalando-incubator/hexo-theme-doc#129]
## Expected Behavior

`swagger_ui` and `swagger_to_html` should render a Swagger spec that contains circular $ref.

## Actual Behavior

`hexo generate` or `hexo server` crash and show the following error:

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  RangeError: Maximum call stack size exceeded
    at Object._prettifyError (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/nunjucks/src/lib.js:36:11)
    at /home/yo/tmp/experiment-hexo/ozd-docs/node_modules/nunjucks/src/environment.js:545:19
    at eval (eval at _compile (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/nunjucks/src/environment.js:615:18), <anonymous>:9:11)
    at tryCatcher (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/yo/tmp/experiment-hexo/ozd-docs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

The issue is at the level of `swagger-ui` and is known (see [UI crashes when the definitions contain circular references](https://github.com/swagger-api/swagger-ui/issues/3012)). It has been already fixed.

The question is: how to force `hexo-theme-doc` to use the fixed version of `swagger-ui`?

## Steps to Reproduce the Problem

  1. have a swagger spec with circular $ref
  2. have a source file that uses `swagger_ui` tag or `swagger_to_html` tag
  3. execute `hexo generate` or `hexo s`

## Specifications

  - NodeJS Version: 6.9.2
  - NPM Version: 3.10.9
  - OS: Ubuntu 14.04
  - Hexo Version: 3.7.1

**Comment by rbarilani** [comment]
@ouadi There isn't way "to force" to use a specific version of swagger_ui at the moment, plus we have to investigate if that's really just a problem of "swagger-ui" or it happens when we parse the spec....

**Comment by ouadi** [comment]
Will it be possible to suggest a work-around for the time being? With this issue, my very first use of Hexo to document an API is completely blocked.
I highly appreciate you help.

**Comment by bhaskarmelkani** [comment]
Hey,

Sincere apologies for a delayed response.
I am updating  the version of `swagger-ui` to the latest version, so it will have the fix for circular references.
For `swagger-to-html`, I will fix the issue but it might take some time.

**Comment by ouadi** [comment]
Many thanks for your valuable help and involvement.
I will wait for the fix.

**Comment by JavaHelper** [comment]
Issue has been raised here: https://stackoverflow.com/questions/57370292/swagger-system-js461-rangeerror-maximum-call-stack-size-exceeded-using-ma

**Comment by JavaHelper** [comment]
@All - Any updates on this please ?
